#!/bin/bash
# Script to move files to the trash in macOS.

# Return an error value if this is not macOS.
if [[ $(uname) != "Darwin" ]]; then
  echo "This script is only for macOS." 1>&2
  exit 1
fi

if [[ $# -gt 0 ]]; then
  a=()
  for f in "$@"; do
    a+=("$(realpath "$f")")
  done
  # Creating a list of POSIX files for AppleScript
  f=$(printf "\", POSIX file \"%s" "${a[@]}")
  osascript -ss -e "tell application \"Finder\" to delete {${f:2}\"}" 1>/dev/null
fi
