import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
args = ["--login"]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[cursor]
style = "Beam"
vi_mode_style = "Beam"

[keyboard]
bindings = [
  # cmd-shift-p opens command search (sends ^R).
  { key = "P", mods = "Command|Shift", chars = "\u0012" },
  # cmd-p opens file search (sends ^T).
  { key = "P", mods = "Command", chars = "\u0014" },
  # cmd-1 through cmd-9 change tmux windows (send ^B #).
  { key = "1", mods = "Command", chars = "\u0002\u0031"},
  { key = "2", mods = "Command", chars = "\u0002\u0032"},
  { key = "3", mods = "Command", chars = "\u0002\u0033"},
  { key = "4", mods = "Command", chars = "\u0002\u0034"},
  { key = "5", mods = "Command", chars = "\u0002\u0035"},
  { key = "6", mods = "Command", chars = "\u0002\u0036"},
  { key = "7", mods = "Command", chars = "\u0002\u0037"},
  { key = "8", mods = "Command", chars = "\u0002\u0038"},
  { key = "9", mods = "Command", chars = "\u0002\u0039"},
]

[font]
size = 16.0

[font.normal]
family = "MesloLGL Nerd Font"

# Uncomment below for custom, colorblind-friendly theme.
#
# [colors.primary]
# background = "#1b1f22"
# foreground = "#b1bac4"
#
# [colors.cursor]
# text = "#30363d"
# cursor = "#e6edf3"
#
# [colors.normal]
# black = "#101010"
# red = "#ff1111"
# green = "#30d158"
# yellow = "#ffd60a"
# blue = "#58a6ff"
# magenta = "#ff37f2"
# cyan = "#53c2c5"
# white= "#b1bac4"
#
# [colors.bright]
# black = "#6e7681"
# red = "#ff4d3d"
# green = "#56d364"
# yellow = "#e3b341"
# blue = "#79c0ff"
# magenta = "#ff2dde"
# cyan = "#22e5ef"
# white = "#d0dae6"
